export const classesData = [
  // ================= workshops CLASSES =================
  {
    id: 1,
    title: 'Basics of Angular',
    description: 'Introductory course for Angular',
    duration: '30 minutes',
    rating: '4.4',
    progress: 70,
    type: 'Basic',
    mode: 'online',
    category: 'workshops',
    image: require('@src/assets/images/avatars/app-academy-tutor-1.png').default
  },
  {
    id: 2,
    title: 'React Fundamentals',
    description: 'Learn React from scratch',
    duration: '1.5 hours',
    rating: '4.6',
    progress: 45,
    type: 'Live',
    mode: 'online',
    category: 'workshops',
    image: require('@src/assets/images/avatars/app-academy-tutor-2.png').default
  },
  {
    id: 3,
    title: 'Node JS Basics',
    description: 'Backend fundamentals with Node',
    duration: '2 hours',
    rating: '4.5',
    progress: 60,
    type: 'Basic',
    mode: 'offline',
    category: 'workshops',
    image: require('@src/assets/images/avatars/app-academy-tutor-3.png').default
  },
  {
    id: 4,
    title: 'UI/UX Design',
    description: 'Design thinking & UI basics',
    duration: '3 hours',
    rating: '4.7',
    progress: 80,
    type: 'Live',
    mode: 'offline',
    category: 'workshops',
    image: require('@src/assets/images/avatars/app-academy-tutor-4.png').default
  },
  {
    id: 5,
    title: 'JavaScript Advanced',
    description: 'Deep dive into JS concepts',
    duration: '2.5 hours',
    rating: '4.8',
    progress: 30,
    type: 'Advanced',
    mode: 'online',
    category: 'workshops',
    image: require('@src/assets/images/avatars/app-academy-tutor-5.png').default
  },
  {
    id: 6,
    title: 'Python for Beginners',
    description: 'Learn Python step by step',
    duration: '1 hour',
    rating: '4.3',
    progress: 55,
    type: 'Basic',
    mode: 'offline',
    category: 'workshops',
    image: require('@src/assets/images/avatars/app-academy-tutor-6.png').default
  },

  // ================= PACKAGE & MEMBERSHIP =================
  {
    id: 7,
    title: 'Full Stack Web Development',
    description: 'Complete frontend + backend package',
    duration: '40 hours',
    rating: '4.9',
    progress: 20,
    type: 'Package',
    mode: 'online',
    category: 'short',
    image: require('@src/assets/images/avatars/app-academy-tutor-1.png').default
  },
  {
    id: 8,
    title: 'UI/UX Mastery Program',
    description: 'Advanced design & prototyping',
    duration: '25 hours',
    rating: '4.8',
    progress: 65,
    type: 'Package',
    mode: 'offline',
    category: 'short',
    image: require('@src/assets/images/avatars/app-academy-tutor-2.png').default
  },
  {
    id: 9,
    title: 'Data Science Membership',
    description: 'Python, ML & analytics',
    duration: '50 hours',
    rating: '4.7',
    progress: 40,
    type: 'Membership',
    mode: 'online',
    category: 'short',
    image: require('@src/assets/images/avatars/app-academy-tutor-3.png').default
  },
  {
    id: 10,
    title: 'Digital Marketing Pro',
    description: 'SEO, Ads & growth hacking',
    duration: '20 hours',
    rating: '4.6',
    progress: 75,
    type: 'Package',
    mode: 'offline',
    category: 'short',
    image: require('@src/assets/images/avatars/app-academy-tutor-4.png').default
  },
  {
    id: 11,
    title: 'Mobile App Development',
    description: 'Android & iOS from scratch',
    duration: '35 hours',
    rating: '4.8',
    progress: 10,
    type: 'Membership',
    mode: 'online',
    category: 'short',
    image: require('@src/assets/images/avatars/app-academy-tutor-5.png').default
  },
  {
    id: 12,
    title: 'Cloud & DevOps Program',
    description: 'AWS, Docker & CI/CD',
    duration: '30 hours',
    rating: '4.7',
    progress: 50,
    type: 'Package',
    mode: 'offline',
    category: 'short',
    image: require('@src/assets/images/avatars/app-academy-tutor-6.png').default
  },
  {
    id: 13,
    title: 'Digital Marketing Pro',
    description: 'SEO, Ads & growth hacking',
    duration: '20 hours',
    rating: '4.6',
    progress: 75,
    type: 'Package',
    mode: 'offline',
    category: 'teacher',
    image: require('@src/assets/images/avatars/app-academy-tutor-4.png').default
  },
  {
    id: 14,
    title: 'Mobile App Development',
    description: 'Android & iOS from scratch',
    duration: '35 hours',
    rating: '4.8',
    progress: 10,
    type: 'Membership',
    mode: 'online',
    category: 'teacher',
    image: require('@src/assets/images/avatars/app-academy-tutor-5.png').default
  },
  {
    id: 15,
    title: 'Cloud & DevOps Program',
    description: 'AWS, Docker & CI/CD',
    duration: '30 hours',
    rating: '4.7',
    progress: 50,
    type: 'Package',
    mode: 'offline',
    category: 'teacher',
    image: require('@src/assets/images/avatars/app-academy-tutor-6.png').default
  },
  {
    id: 16,
    title: 'Digital Marketing Pro',
    description: 'SEO, Ads & growth hacking',
    duration: '20 hours',
    rating: '4.6',
    progress: 75,
    type: 'Package',
    mode: 'offline',
    category: 'retreat',
    image: require('@src/assets/images/avatars/app-academy-tutor-4.png').default
  },
  {
    id: 17,
    title: 'Mobile App Development',
    description: 'Android & iOS from scratch',
    duration: '35 hours',
    rating: '4.8',
    progress: 10,
    type: 'Membership',
    mode: 'online',
    category: 'retreat',
    image: require('@src/assets/images/avatars/app-academy-tutor-5.png').default
  },
  {
    id: 18,
    title: 'Cloud & DevOps Program',
    description: 'AWS, Docker & CI/CD',
    duration: '30 hours',
    rating: '4.7',
    progress: 50,
    type: 'Package',
    mode: 'offline',
    category: 'retreat',
    image: require('@src/assets/images/avatars/app-academy-tutor-6.png').default
  },
  {
    id: 19,
    title: 'Cloud & DevOps Program',
    description: 'AWS, Docker & CI/CD',
    duration: '30 hours',
    rating: '4.7',
    progress: 50,
    type: 'Package',
    mode: 'offline',
    category: 'therapy',
    image: require('@src/assets/images/avatars/app-academy-tutor-6.png').default
  },
  {
    id: 20,
    title: 'Digital Marketing Pro',
    description: 'SEO, Ads & growth hacking',
    duration: '20 hours',
    rating: '4.6',
    progress: 75,
    type: 'Package',
    mode: 'offline',
    category: 'therapy',
    image: require('@src/assets/images/avatars/app-academy-tutor-4.png').default
  },
  {
    id: 21,
    title: 'Mobile App Development',
    description: 'Android & iOS from scratch',
    duration: '35 hours',
    rating: '4.8',
    progress: 10,
    type: 'Membership',
    mode: 'online',
    category: 'therapy',
    image: require('@src/assets/images/avatars/app-academy-tutor-5.png').default
  },
  {
    id: 22,
    title: 'Cloud & DevOps Program',
    description: 'AWS, Docker & CI/CD',
    duration: '30 hours',
    rating: '4.7',
    progress: 50,
    type: 'Package',
    mode: 'offline',
    category: 'therapy',
    image: require('@src/assets/images/avatars/app-academy-tutor-6.png').default
  }
]
